services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/conversations_db
    volumes:
      - .:/app

  llm:
    build: https://github.com/bankai254/llm-python-program.git 
    container_name: llm_app
    environment:
      - HF_TOKEN=
    ports:
      - "8000:8000"
    volumes:
      - .:/llm-app

volumes:
  mongodb_data:
